// Top-level build file
apply from: "variables.gradle"

buildscript {
    ext {
        // Définir les versions
        kotlin_version = '1.9.22'
        agp_version = '8.7.3'
    }
    
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // Firebase / Google Services (nécessaire pour les notifications push)
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}